spring.datasource.url=jdbc:postgresql://localhost:5432/office_day_scheduler
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
server.port = 8090
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
ods.app.secret=odscheduler
ods.expires.in=3600000
refresh.token.expires.in=604800

spring.jpa.defer-datasource-initialization=never
spring.sql.init.mode=always